### ISSUE TITLE
Unable to #update_customer_payment_profile(options) with masked card / masked exp

### ISSUE THREAD

**Issue by jgrannas** [Shopify/active_merchant#1509]
Authorize.net documentation says that i can update a payment_profile in their CIM using a masked card and masked expiration...

I want to update a payment_profile bill_to address, but cannot get anything to go through. As documentation states, I tried first using a get of the payment_profile, and modifying those values, but even that did not work. So i am manually creating the options hash just to try and get this to work.

```
def update_cim_payment_profile 
    options = {
        :customer_profile_id => user.customer_profile_id,
        :payment_profile => {
          :customer_payment_profile_id => customer_payment_profile_id,
          :bill_to => {
            :first_name => "John",
            :last_name => "Smith"
          },
          :payment => {
            :credit_card => {
              :card_number => "XXXX5544",
              :expiration_date => "XXXX"
            }
          }
        }
      } 
    response = GATEWAY.update_customer_payment_profile(options)
end
```

I am getting
```
NoMethodError: undefined method `number' for {:card_number=>"XXXX5544", :expiration_date=>"XXXX"}:Hash
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activemerchant-1.45.0/lib/active_merchant/billing/gateways/authorize_net_cim.rb:802:in `block in add_credit_card'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activemerchant-1.45.0/lib/active_merchant/billing/gateways/authorize_net_cim.rb:800:in `add_credit_card'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activemerchant-1.45.0/lib/active_merchant/billing/gateways/authorize_net_cim.rb:761:in `block in add_payment_profile'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activemerchant-1.45.0/lib/active_merchant/billing/gateways/authorize_net_cim.rb:760:in `add_payment_profile'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activemerchant-1.45.0/lib/active_merchant/billing/gateways/authorize_net_cim.rb:596:in `block in build_update_customer_payment_profile_request'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activemerchant-1.45.0/lib/active_merchant/billing/gateways/authorize_net_cim.rb:595:in `build_update_customer_payment_profile_request'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activemerchant-1.45.0/lib/active_merchant/billing/gateways/authorize_net_cim.rb:500:in `block in build_request'
... 24 levels...
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activerecord-4.1.5/lib/active_record/transactions.rb:208:in `transaction'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activerecord-4.1.5/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activerecord-4.1.5/lib/active_record/transactions.rb:268:in `block in save'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activerecord-4.1.5/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/activerecord-4.1.5/lib/active_record/transactions.rb:267:in `save'
	from (irb):80
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/railties-4.1.5/lib/rails/commands/console.rb:90:in `start'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/railties-4.1.5/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.1.2@kranix/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'2.1.2 :081
```

I looked at line 802 in the gateway source... and you guys are allowing a masked card number it seems... so where am I going wrong here.
xml.tag!('cardNumber', full_or_masked_card_number(credit_card.number))

**Comment by jgrannas** [comment]
I was able to get this to work, but it's a little bit odd. After reading through the methods, I found this:

```
xml.tag!('cardNumber', full_or_masked_card_number(credit_card.number))
```

So it's expecting an credit_card object instead of a hash (credit_card[:card_number]). I had to create an object and pass it into the hash. So if you want to update a payment with using only the last four digits, you will need to get weird.

```
      cc = ActiveMerchant::Billing::CreditCard.new(
        :number => 5544
      )
      options = {
        :customer_profile_id => user.customer_profile_id.to_s,
        :payment_profile => {
          :customer_payment_profile_id => customer_payment_profile_id,
          :bill_to => {
            :first_name => "John",
            :last_name => "Smith"
          },
          :payment => {
            :credit_card => cc
          }
        }
      } 
      response = GATEWAY.update_customer_payment_profile(options)
```
