### ISSUE TITLE
An error occured while validating credit card

### ISSUE THREAD

**Issue by artlugovoy** [Shopify/active_merchant#1667]
CreditCard#validate method fails with this:

```
NoMethodError: undefined method `+' for nil:NilClass
... /active_merchant/billing/credit_card.rb:237:in `validate'
```

Gem version is 1.48 
It seems like validate_essential_attributes method returns nil instead of empty array.

**Comment by larrylv** [comment]
@artlugovoy Could you please provide more details or a re-produce script? Because from the codes of `validate_essential_attributes` method, it will always return an array.

**Comment by artlugovoy** [comment]
@larrylv I'm using ruby 1.9.3-p327 and the code is:

```ruby
credit_card = ActiveMerchant::Billing::CreditCard.new(
    number: '4111111111111111',
    month: 12,
    year: 18,
    first_name: 'Test',
    last_name: 'User',
    verification_value: '123'
  )

credit_card.validate # it causes the error
```

Of course the code seems okay, but in fact I have the error described above

**Comment by larrylv** [comment]
@artlugovoy Thanks for the reproduce codes, but I run it and the error didn't occur.

``` bash
➜  ~/Code/Hacks/active_merchant ruby:(1.9.3-p551)
$ git co v1.48.0
$ git log --oneline -1
3120ee2 Version 1.48.0
➜  ~/Code/Hacks/active_merchant ruby:(1.9.3-p551)
$ pry
[1] pry(main)> $:.unshift "./lib"
[2] pry(main)> require 'active_merchant'
=> true
[3] pry(main)> ActiveMerchant::VERSION
=> "1.48.0"
[4] pry(main)> credit_card = ActiveMerchant::Billing::CreditCard.new(
[4] pry(main)*   number: '4111111111111111',
[4] pry(main)*   month: 12,
[4] pry(main)*   year: 18,
[4] pry(main)*   first_name: 'Test',
[4] pry(main)*   last_name: 'User',
[4] pry(main)*   verification_value: '123'
[4] pry(main)* )
=> #<ActiveMerchant::Billing::CreditCard:0x007fe9d0a2ac30 @first_name="Test", @last_name="User", @month=12, @number="4111111111111111", @verification_value="123", @year=18>
[5] pry(main)> credit_card.validate
=> {:year=>["expired"]}
```

The only difference is I used `1.9.3-p551`, but I don't think it is relevant.

Could you confirm that you are using `1.48.0` version? You may output it with `puts ActiveMerchant::VERSION`.

Thanks.

**Comment by larrylv** [comment]
@artlugovoy And if I change the year from `18` to `2018`, `credit_card.validate` got an empty hash which means no errors.

**Comment by artlugovoy** [comment]
@larrylv I'm sorry, it returns correct hash with errors if I specify expiration year like this "18" but it fails when I set the year to "2018"

```ruby
[8] pry(main)> ActiveMerchant::VERSION
=> "1.48.0"
[9] pry(main)> credit_card = ActiveMerchant::Billing::CreditCard.new(
[9] pry(main)*       number: '4111111111111111',
[9] pry(main)*       month: 12,
[9] pry(main)*       year: 18,
[9] pry(main)*       first_name: 'Test',
[9] pry(main)*       last_name: 'User',
[9] pry(main)*       verification_value: '123'
[9] pry(main)*     )
=> #<ActiveMerchant::Billing::CreditCard:0x000000099d8178
 @first_name="Test",
 @last_name="User",
 @month=12,
 @number="4111111111111111",
 @verification_value="123",
 @year=18>
[10] pry(main)> credit_card.validate
/home/arthur/.rvm/gems/ruby-1.9.3-p327@backoffice/gems/activemerchant-1.48.0/lib/active_merchant/billing/compatibility.rb:11:in `errors': Implicit inclusion of Rails-specific functionality is deprecated. Explicitly require "active_merchant/billing/rails" if you need it.
/home/arthur/.rvm/gems/ruby-1.9.3-p327@backoffice/gems/activemerchant-1.48.0/lib/active_merchant/billing/compatibility.rb:11:in `errors': Implicit inclusion of Rails-specific functionality is deprecated. Explicitly require "active_merchant/billing/rails" if you need it.
=> {"expired"=>[nil], "is not a valid year"=>[nil]}
[11] pry(main)> credit_card.year = 2018 
=> 2018
[12] pry(main)> credit_card.validate
NoMethodError: undefined method `+' for nil:NilClass
from /home/arthur/.rvm/gems/ruby-1.9.3-p327@backoffice/gems/activemerchant-1.48.0/lib/active_merchant/billing/credit_card.rb:236:in `validate'

**Comment by artlugovoy** [comment]
@larrylv  I've created application from scratch using 1.93.-p551 and everything works well!

**Comment by larrylv** [comment]
Huh? That's weird. But glad you solved that problem.

**Comment by larrylv** [comment]
@artlugovoy I think that's related with your `activesupport` version, but nothing to do with ruby version. Feel free to talk with me if you want to dig into this. Email should be fine. :-)
